### ISSUE TITLE
TODO: Alpha release

### ISSUE THREAD

**Issue by JonasBa** [getsentry/profiling-node#5]
**TODO:**
- [x] **Setup CI** (test, lint...)
- [x] **Ensure bindings compile across ubuntu, macos and windows runners**
- [x] **Adopt new sampled format**
       https://github.com/getsentry/relay/pull/1462
- [x] **Collect threadID**
       https://chromium.googlesource.com/v8/v8/+/97f4baaacd782240c0ceb87141d713564a15ef77/src/isolate.cc
18.2/d3/dda/classv8_1_1_cpu_profiling_options.html
- [x] **Add support for profiles_sample_rate**
   Python example https://github.com/getsentry/sentry-python/pull/1613
- [x] **Strip out all logger calls**
- [x] **Check if profiler profiles all threads by default** 
       Cpu Profiles are scoped to threads
       We are not specifying any filter_context as per https://v8docs.nodesource.com/node-
- [x] **Tests**
- [x] **How do we handle multiple overlapping transactions**
       If transactions have the same name and they are overlapping, calling stop on any of them will cause all of them to be stopped.
- [x] **What happens with spawn/fork**
       Same behavior as workers
- [x] **Benchmark process memory with/without profiler**
       Ensure we are not leaking memory as per https://bugs.chromium.org/p/v8/issues/detail?id=6623.
       It seems versions > 12 are not impacted. I measured memory before and after running 1k profiles (directly calling bindings) and there was a very slight increase of only ~45kb at the end of the run.
- [x] **What happens in the event of a profiler crash?**
        Segfaults will crash everything (even the main thread) if their source is from a worker.
- [x] **Add profile safeguards (duration+stack depth)**
       Tbd if we need them, check with our other SDK's on what limitations we have
- [x] **Perf (try and reducer overhead)**
      There are a couple of places where we could do better (right now we iterate over all samples to assign a thread_id which can result in a loop over a large N of items)
- [x] **Readme**
- [x] **License**
- [x] **Docs**
- [x] **Setup Github boilerplate** (issue/pr template)
- [x] **Publish alpha**
- [x] **Open private access (internal/external)**

**Partial:**
- [x] **Worker support** 
   See WORKERS.md
   https://v8docs.nodesource.com/node-18.2/d3/dda/classv8_1_1_cpu_profiling_options.html

**Deferred:**
- [ ] **Allow setting sampleInterval**
       tbd if changing between profiles is possible as the profiler instance is reused, https://v8docs.nodesource.com/node-18.2/d2/dc3/namespacev8.html#a4bd7d7853694d74bbd6bbc91f96e4315 could be helpful to know if we can dispose and create a new v8::CpuProfiler with new options. 
- [ ] **Allow setting usePreciseSampling**
        same tbd as ^
- [ ] **Allow setting of kLazyLogging/kEagerLogging**
        Allowing this to be set can help manage overhead for short lived programs.

- [ ] **Integrate into sentry codebase (npm link and test on jest, sourcemaps.io, webpack build?)**
        This can wait for beta

The above 3 items are deferred as none of our other SDK's allow anything similar. For the purpose of the alpha release we can just settle on defaults.

- [ ] **Add node v10 to test matrix**
         It would be nice to have this working, but CI currently throws https://github.com/nodejs/help/issues/2134 and I dont want to waste too long setting this up.
